### ISSUE TITLE
Doesn't work with 32 bit Windows

### ISSUE THREAD

**Issue by bamhm182** [bamhm182/FinTrinity#10]
It just downloads psvitaimgtools for 64-bit. Had a user request for it to differentiate and download the 32-bit version where required.

**Comment by bamhm182** [comment]
arnii reported in #11 that it doesn't work, but I pushed some code that I was expecting it to work with last night. I don't recall if the most recent release on the releases page contains the fix. arnii, can you make sure to download directly the most recent version [here](https://github.com/bamhm182/FinTrinity/archive/master.zip) and let me know if it works for you? If not, what error message does it give you?

**Comment by pochopsp** [comment]
@bamhm182 thanks for your amazing work. Just tested it on my Windows 10 Acer 32 bit netbook and it works flawlessly :)

**Comment by bamhm182** [comment]
Awesome! I'm just happy to be able to help. Glad it worked for you. Thanks for testing it and letting me know!
