### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by mbellman** [bamhm182/FinTrinity#14]
Platform: Windows 10 64-bit
Python installation: 3.7.3
FinTrinity version: 0.5 (Python 3.7.3 Version)

Steps taken:

1. Double-click and run `GUI.py`
2. Command prompt opens, FinTrinity prompt appears, correct game is preselected
3. Confirm game selection
4. The following error/stack trace appears in the command prompt:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\[...]\FinTrinity-v0.5-Python\GUI.py", line 76, in click_confirm
    self.fin.setup_dirs()
  File "C:\Users\[...]\FinTrinity-v0.5-Python\FinTrinity.py", line 73, in setup_dirs
    self.working_dir = Utils.make_dir(base_dir / f"FinTrinity{Utils.get_timestamp()}")
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

Clearly the Python runtime doesn't like the presence of a particular `/` operator in the argument to `Utils.make_dir`, but I don't know why, seeing as there are other spots in the code where `/` is used to operate on strings. I'm not familiar enough with Python to understand the cause of the hangup.

**Comment by mbellman** [comment]
**Update 2**: Boom. `base_dir` needed to be initialized to `Path(os.getcwd())` in order for everything to work properly. I'd open a PR but I don't know enough about your development/build/testing pipeline to feel comfortable submitting the change yet.

----

**Update**: I was able to bypass the initial error by changing the following line:

`FinTrinity.py, L66`
```
base_dir = "C:"
``` 

to

```
base_dir = Path("C:")
````

However, the output reports that `Decryption Failed`. I am seeing a folder generated with backup/decrypted/hacked subfolders though.

**Comment by bamhm182** [comment]
Thanks! Somehow I missed this issue for a while. I have added the changes and confirmed they worked.
