### ISSUE TITLE
GUI.py refuses to load on Win10, gives UnicodeDecodeError

### ISSUE THREAD

**Issue by ArtificialRaccoon** [bamhm182/FinTrinity#8]
Steps to reproduce (on my machine):

1. Downloaded the current release, and unarchived it locally.
2. Installed Python 3.7.3
3. Opened command prompt, navigated to FinTrinity folder
4. Ran GUI.py with:  pyhton GUI.py

```
Got the following output:
  File "GUI.py", line 49, in <module>
    gui = GUI()
  File "GUI.py", line 8, in __init__
    self.fin.read_registry()
  File "C:\Users\Wear\Downloads\FinTrinity-v0.1\FinTrinity.py", line 26, in read_registry
    self.user.set_path(self.apps_path)
  File "C:\Users\Wear\Downloads\FinTrinity-v0.1\classes\User.py", line 25, in set_path
    self.get_games()
  File "C:\Users\Wear\Downloads\FinTrinity-v0.1\classes\User.py", line 35, in get_games
    game.set_path(self.path)
  File "C:\Users\Wear\Downloads\FinTrinity-v0.1\classes\Game.py", line 18, in set_path
    self.set_title()
  File "C:\Users\Wear\Downloads\FinTrinity-v0.1\classes\Game.py", line 22, in set_title
    clean = sub(".u[0-9a-f]{4}", "", dumps(fp.read()))
  File "C:\Users\Wear\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 224: character maps to <undefined>
```

Not sure where my system differs from yours/others.  Thoughts?

**Comment by bamhm182** [comment]
It appears that it doesn't like your game's name or maybe some other
information in there? Can you please attach the param.sfo file from
sce_sys? I think I know how to fix it, but I would like to make sure it
works. Should be an easy fix I can do tonight.

**Comment by bamhm182** [comment]
Also, thank you for the posting and formatting of this issue. :)

**Comment by ArtificialRaccoon** [comment]
@bamhm182 No problem.  I'm at work, but I'll try and send you the param.sfo file tonight.

I assume it would be the very first game in QCMA's PSP list which is causing this issue (BOF3 iirc)?  It doesn't even get to loading the GUI, so I'm not sure what it detected.

**Comment by bamhm182** [comment]
I just got off work and started poking around. Depending on when you get off work, it may or may not be fixed, either way, if you could provide that param.sfo, I would appreciate it. I currently have it going after the folder with the most recently modified date, so if you sort your folders by date, it is whichever one would be on top.

**Comment by ArtificialRaccoon** [comment]
[param.zip](https://github.com/bamhm182/FinTrinity/files/3175137/param.zip)

Looks like it was Class of Heroes 2

**Comment by bamhm182** [comment]
Thanks! It seems like it was working for me, but I put in some code that should better handle it just in case. Please test release v0.2 and let me know if it works for you. :)

**Comment by ArtificialRaccoon** [comment]
No problem.
Sadly, still no go on my end.  I downloaded the executable (I assume that was all I needed?), and ran it via the command line.  I ended up with this as the output:

```
Traceback (most recent call last):
  File "GUI.py", line 49, in <module>
  File "GUI.py", line 8, in __init__
  File "FinTrinity.py", line 33, in read_registry
  File "classes\User.py", line 35, in set_path
  File "classes\User.py", line 50, in get_games
  File "classes\Game.py", line 18, in set_path
  File "classes\Game.py", line 23, in set_title
  File "c:\users\bamhm\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 224: character maps to <undefined>
[18604] Failed to execute script GUI
```

Based upon the last little bit there; I think you might have hard-coded your own path to the python installation?

**Comment by bamhm182** [comment]
Can I bother you to try it with the zip?  It seems like the way I built the exe may have hard coded some things...

**Comment by ArtificialRaccoon** [comment]
Sure thing.  
Looks like the same output as I had originally with v0.1:

```
Traceback (most recent call last):
  File "GUI.py", line 49, in <module>
    gui = GUI()
  File "GUI.py", line 8, in __init__
    self.fin.read_registry()
  File "C:\Users\Wear\Downloads\FinTrinity\FinTrinity.py", line 33, in read_registry
    self.user.set_path(self.apps_path)
  File "C:\Users\Wear\Downloads\FinTrinity\classes\User.py", line 35, in set_path
    self.get_games()
  File "C:\Users\Wear\Downloads\FinTrinity\classes\User.py", line 50, in get_games
    game.set_path(self.path)
  File "C:\Users\Wear\Downloads\FinTrinity\classes\Game.py", line 18, in set_path
    self.set_title()
  File "C:\Users\Wear\Downloads\FinTrinity\classes\Game.py", line 23, in set_title
    clean = sub(".u[0-9a-f]{4}", "", dumps(fp.read()))
  File "C:\Users\Wear\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 224: character maps to <undefined>
```

I've confirmed that I'm running Python 3.7.3; but I'm going to try reinstalling it for good measure.

Back in a few.

**Comment by ArtificialRaccoon** [comment]
So, reinstalled P3.7.3; same results.
I also just downloaded the P3.7.3 x64 release, and tried that; same results.

Are you sure it's taking the last modified PSP game in the list?  Maybe it's actually taking another game, which has something not handled.  

I see that "Crimson Gem Saga" has the trademark symbol in its name.  That's the only odd one in my backup list.  I've attached its sfo just to see.

[param.zip](https://github.com/bamhm182/FinTrinity/files/3175444/param.zip)

Sorry to be frustrating!

**Comment by bamhm182** [comment]
DOH! I feel like an idiot. I guess somewhere along the lines I removed the code that I had put in to fix this issue. Not exactly sure when/how that happened. Please try to redownload from the Releases page.

I've been using LocoRoco that has the TM symbol. REally not sure what issue your computer is having with that param.sfo.

You're far from frustrating. What's frustrating is when something is broke and I get zero useful feedback as to what it's doing wrong.

**Comment by bamhm182** [comment]
What's really strange is that I have no problem with either param.sfo that you've provided even on older builds. Can you check that "C:\Users\Wear\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py" exists?

**Comment by ArtificialRaccoon** [comment]
Yup, file exists.  
I also downloaded the updated code you added (just FinTrinity.py), and no change.

It's obviously something with my machine, so lets think about the deltas my machine might have...

It's a Win10, x64 image.  I'm running in English (Canadian).  I have at least 50gb free, and I've got 16gb of ram (with at least 50% free).  

Perhaps a change in the python code where it spits out what file its attempting to open, before it gets to this point?

**Comment by ArtificialRaccoon** [comment]
Wait, hold up - I just downloaded the entire repo (not just the updated FinTrinity.py), and the GUI has finally appeared.

Your last checkin does appear to have fixed it!

**Comment by ArtificialRaccoon** [comment]
Perhaps spoke too soon again:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Wear\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "GUI.py", line 40, in click_confirm
    self.fin.setup_dirs()
  File "C:\Users\Wear\Downloads\FinTrinity-master\FinTrinity.py", line 46, in setup_dirs
    self.working_dir = Utils.make_dir(Utils.get_home() / "Desktop" / f"FinTrinity{Utils.get_timestamp()}")
  File "C:\Users\Wear\Downloads\FinTrinity-master\classes\Utils.py", line 38, in make_dir
    os.makedirs(d)
  File "C:\Users\Wear\AppData\Local\Programs\Python\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Wear\\Desktop\\FinTrinity2019513-21598'
```

**Comment by bamhm182** [comment]
Dang. Getting closer!

It's almost like your computer just doesn't want to acknowledge that "C:\Users\Wear\" is real... Are you currently logged into the "Wear" user?

**Comment by bamhm182** [comment]
[GUI.zip](https://github.com/bamhm182/FinTrinity/files/3175580/GUI.zip)

Can I get you to try this one? I changed how it gets the Desktop folder.

**Comment by ArtificialRaccoon** [comment]
The executable in the zip has the same issue as we were having before, for some reason.
And yup, it's the only account on the machine.

**Comment by bamhm182** [comment]
I figured it probably would... I thought it might be worth a try, though. 

I don't fully understand what it wants... It checks to see if the file exists. It doesn't, so it tries to create it, but then it complains that it cannot create it because it doesn't exist...

**Comment by ArtificialRaccoon** [comment]
Thought:  Could this be a permissions issue (the failure to create a folder on the desktop)?

I don't get any UAC popups, nor does the "protected folders" warning appear.  Still, it might be blocking the write from occouring.

I don't know python myself; is there a way to catch a specific exception?

**Comment by bamhm182** [comment]
AFAIK, that's about as specific as it will get. It seems like it could be some sort of issue creating a folder on the desktop. Do you run any antivirus or something that could be messing with this?

**Comment by ArtificialRaccoon** [comment]
Nothing out of the ordinary; just Windows Defender.

I have to run, but I did a quick test.  I opened the python interpreter, and attempted to create a folder on the desktop as well.  It failed.

If I attempt to create a folder in the root, it works fine.

I'll try disabling Windows Defender tomorrow, and see if that quells the issue.  Really looks like a permissions issue.

**Comment by bamhm182** [comment]
That's pretty strange. I wonder what's stopping it. Maybe I can do a check "Can I write to your desktop? No. Can I write to 'C:\'"? Seems weird that I would be able to write to C:\, but not your Desktop. Oh well. I'll add that, make a push and head to bed myself. We'll see how it works for you tomorrow.

Take care and thanks for helping me look into this so much.

EDIT: It has been pushed. Just download the zip from the main page rather than the releases page and test that when you get a moment. Thanks in advance!

**Comment by ArtificialRaccoon** [comment]
Sorry about the delay:

(Today was a success)

1.  I disabled Controlled Folder Access and Windows Defender
2.  I cloned the repo
3.  I opened a command prompt and navigated to the FinTrinity repo
4.  I ran GUI.py

And... It worked!  I suspect this was all due to either Windows Defender or the new Controlled Folder access.  Surprising that it didn't give a popup that Python was trying to access something; though thats not your problem.

Class of Heroes 2 patched without an issue.  I guess the end result of this should be to mention disabling either of those two things to ensure it works as expected?

**Comment by bamhm182** [comment]
That's pretty strange, but hey! Glad you got it working. I'll take a look at the controlled folder access and see if there is anything I can do to alert the user about that. Thanks for all your troubleshooting!

**Comment by bamhm182** [comment]
Closing since the original issue was fixed. If anyone comes across this for the Controlled Folder Access thing, you should be able to type "Controlled Folder Access" into the Windows search bar and add FinTrinity through the "Allow an app through Controlled Folder Access" option in the window that appears.
